In [1]:
# Numpy

In [2]:
## list to array
import numpy as np
my_list = [1,3,24,5,6]
np.array(my_list)


array([ 1,  3, 24,  5,  6])

In [3]:
type(np.array(my_list))

numpy.ndarray

In [4]:
## list to 2D array 2*3

rio_list = [[1,3,24,5,6], [1,3,24,5,6]]
np.array(rio_list)

array([[ 1,  3, 24,  5,  6],
       [ 1,  3, 24,  5,  6],
       [ 1,  3, 24,  5,  6]])

In [5]:
type(np.array(rio_list))

numpy.ndarray

In [6]:
## list to 3D array 3*3
sio_list = [[1,3,24,5,6], [1,3,24,5,6], [1,3,24,5,6]]
np.array(sio_list)

array([[ 1,  3, 24,  5,  6],
       [ 1,  3, 24,  5,  6],
       [ 1,  3, 24,  5,  6]])

In [10]:
# type.dtype

new_list = [1,3,24,5,6]
arr = np.array(new_list)

arr.dtype

dtype('int32')

In [12]:
# type.dshape m=col. n=row
new_list = [1,3,24,5,6]
arr = np.array(new_list)

arr.shape

(5,)

In [14]:
old_list = [[1,3,24], [1,5,6], [24,5,6]]
arr = np.array(old_list)

arr.shape

(3, 3)

In [16]:
import numpy as np
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# zeros
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

 other functions like linespace, rand, randn, randint

In [22]:
# Pandas

In [23]:
import pandas as pd
my_list = [10,20,30,40]
series = pd.Series(my_list)

In [24]:
series

0    10
1    20
2    30
3    40
dtype: int64

In [25]:
series.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
series.values

array([10, 20, 30, 40], dtype=int64)

In [28]:
# creating series from numpy array
import numpy as np
import pandas as pd

index = ['a','b','c','d']
arr = np.array([10,20,30,40])

pd.Series(data=arr, index=index)

a    10
b    20
c    30
d    40
dtype: int32

In [33]:
# creating series from dictionary
d = {'a':10, 'b':20, 'c':30}
pd.Series(d)


a    10
b    20
c    30
dtype: int64

In [34]:
type(pd.Series(d))

pandas.core.series.Series

In [35]:
# Datafram

In [38]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[2,3,4,], 
                  [2,3,4,], 
                  [2,3,4,],
                  [3,4,2]])
df

0  1  2
0  2  3  4
1  2  3  4
2  2  3  4
3  3  4  2

In [39]:
print("Shape ", df.shape)

Shape  (4, 3)


In [40]:
print("Index ", df.index)

Index  RangeIndex(start=0, stop=4, step=1)


In [43]:
df2 = pd.DataFrame([[1,2,3],[4,5,6],[6,5,4],[2,3,4]], index=['a','b','c','d'], columns=['x','y','z'])

In [44]:
df2

x  y  z
a  1  2  3
b  4  5  6
c  6  5  4
d  2  3  4

In [45]:
# read the data into dataframe

In [48]:
weather_df = pd.read_csv("data/weather_2012.csv")
print("Shape ", weather_pdf.shape)
print("Index ", weather_pdf.index)

Shape  (8784, 8)
Index  RangeIndex(start=0, stop=8784, step=1)


In [49]:
weather_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [51]:
weather_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [52]:
# converting datetime into datetime object
weather_df['Date/Time'] = pd.to_datetime(weather_df['Date/Time'])

In [53]:
weather_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

In [55]:
# give all info about data
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB


In [58]:
# first 5 record
weather_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [59]:
# last 5 reord
weather_df.tail()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa) Weather  
8779               30              9.7           100.13    Snow  
8780               24              9.7           100.03    Snow  
8781               28              4.8            99.95    Snow  
8782               28              9.7            99.91    Snow  
8783               30             11.3            99.89    Snow

In [61]:
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [67]:
# unique values in series
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [69]:
# exactly kitne unique hai
weather_df['Weather'].nunique()

50

In [70]:
weather_df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                        

In [71]:
# Data manipulation and Transformation

In [72]:
col = weather_df['Weather']

print(type(col))
col.head()

<class 'pandas.core.series.Series'>


0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

In [73]:
twocol = weather_df[['Weather', 'Temp (C)']]

print(type(col))
twocol.head()

<class 'pandas.core.series.Series'>


Weather  Temp (C)
0                   Fog      -1.8
1                   Fog      -1.8
2  Freezing Drizzle,Fog      -1.8
3  Freezing Drizzle,Fog      -1.5
4                   Fog      -1.5

In [76]:
# get 25 rows
weather_df[:25]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   
5  2012-01-01 05:00:00      -1.4                -3.3           87   
6  2012-01-01 06:00:00      -1.5                -3.1           89   
7  2012-01-01 07:00:00      -1.4                -3.6           85   
8  2012-01-01 08:00:00      -1.4                -3.6           85   
9  2012-01-01 09:00:00      -1.3                -3.1           88   
10 2012-01-01 10:00:00      -1.0                -2.3           91   
11 2012-01-01 11:00:00      -0.5                -2.1           89   
12 2012-01-01 12:00:00      -0.2                -2.0           88   
13 2012-01-01 13:00:00       0.2                -1.7           87   
14 2012-01-01 14:00:00       0.8                -1.1           87   
15 2012-01-01 15:00:00       1.8                -0.4           85   
16 2012-01-01 16:00:00       2.6                -0.2           82   
17 2012-01-01 17:00:00       3.0                 0.0           81   
18 2012-01-01 18:00:00       3.8                 1.0           82   
19 2012-01-01 19:00:00       3.1                 1.3           88   
20 2012-01-01 20:00:00       3.2                 1.3           87   
21 2012-01-01 21:00:00       4.0                 1.7           85   
22 2012-01-01 22:00:00       4.4                 1.9           84   
23 2012-01-01 23:00:00       5.3                 2.0           79   
24 2012-01-02 00:00:00       5.2                 1.5           77   

    Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                 4              8.0           101.24                   Fog  
1                 4              8.0           101.24                   Fog  
2                 7              4.0           101.26  Freezing Drizzle,Fog  
3                 6              4.0           101.27  Freezing Drizzle,Fog  
4                 7              4.8           101.23                   Fog  
5                 9              6.4           101.27                   Fog  
6                 7              6.4           101.29                   Fog  
7                 7              8.0           101.26                   Fog  
8                 9              8.0           101.23                   Fog  
9                15              4.0           101.20                   Fog  
10                9              1.2           101.15                   Fog  
11                7              4.0           100.98                   Fog  
12                9              4.8           100.79                   Fog  
13               13              4.8           100.58                   Fog  
14               20              4.8           100.31                   Fog  
15               22              6.4           100.07                   Fog  
16               13             12.9            99.93         Mostly Cloudy  
17               13             16.1            99.81                Cloudy  
18               15             12.9            99.74                  Rain  
19               15             12.9            99.68                  Rain  
20               19             25.0            99.50                Cloudy  
21               20             25.0            99.39                Cloudy  
22               24             19.3            99.32          Rain Showers  
23               30             25.0            99.31                Cloudy  
24               35             25.0            99.26          Rain Showers

In [86]:
# slice and select the number of columns
weather_df[['Date/Time', 'Visibility (km)']][0:10:2]

Date/Time  Visibility (km)
0 2012-01-01 00:00:00              8.0
2 2012-01-01 02:00:00              4.0
4 2012-01-01 04:00:00              4.8
6 2012-01-01 06:00:00              6.4
8 2012-01-01 08:00:00              8.0

In [ ]:
# best way use .loc OR .iloc for selection and extraction of column

In [91]:
# go on label basis
weather_df.loc[0:5, ['Date/Time', 'Visibility (km)']]

Date/Time  Visibility (km)
0 2012-01-01 00:00:00              8.0
1 2012-01-01 01:00:00              8.0
2 2012-01-01 02:00:00              4.0
3 2012-01-01 03:00:00              4.0
4 2012-01-01 04:00:00              4.8
5 2012-01-01 05:00:00              6.4

In [92]:
# .iloc go on index basis
weather_df[ ['Date/Time', 'Visibility (km)']].iloc[0:5]

Date/Time  Visibility (km)
0 2012-01-01 00:00:00              8.0
1 2012-01-01 01:00:00              8.0
2 2012-01-01 02:00:00              4.0
3 2012-01-01 03:00:00              4.0
4 2012-01-01 04:00:00              4.8

In [93]:
# Filtering

In [94]:
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [96]:
snowed_filter = weather_df['Weather'].str.lower().str.contains('snow')

In [97]:
snowed_filter

0       False
1       False
2       False
3       False
4       False
        ...  
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

In [98]:
weather_df[snowed_filter]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
41   2012-01-02 17:00:00      -2.1                -9.5           57   
44   2012-01-02 20:00:00      -5.6               -13.4           54   
45   2012-01-02 21:00:00      -5.8               -12.8           58   
47   2012-01-02 23:00:00      -7.4               -14.1           59   
48   2012-01-03 00:00:00      -9.0               -16.0           57   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)       Weather  
41                 22             25.0            99.66  Snow Showers  
44                 24             25.0           100.07  Snow Showers  
45                 26             25.0           100.15  Snow Showers  
47                 17             19.3           100.27  Snow Showers  
48                 28             25.0           100.35  Snow Showers  
...               ...              ...              ...           ...  
8779               30              9.7           100.13          Snow  
8780               24              9.7           100.03          Snow  
8781               28              4.8            99.95          Snow  
8782               28              9.7            99.91          Snow  
8783               30             11.3            99.89          Snow  

[583 rows x 8 columns]

In [ ]:
# Working with columns operations arithmatic

In [101]:
weather_df['Wind Spd (km/h)'].head() 

0    4
1    4
2    7
3    6
4    7
Name: Wind Spd (km/h), dtype: int64

In [102]:
weather_df['Wind Spd (km/h)'].head() + 2

0    6
1    6
2    9
3    8
4    9
Name: Wind Spd (km/h), dtype: int64

In [103]:
# Custom functions  .apply()
def times2(value):
    return value * 2

In [106]:
t2 = weather_df['Visibility (km)'].apply(times2).head()

In [107]:
t2

0    16.0
1    16.0
2     8.0
3     8.0
4     9.6
Name: Visibility (km), dtype: float64

In [108]:
weather_df['Visibility (km)'].describe()

count    8784.000000
mean       27.664447
std        12.622688
min         0.200000
25%        24.100000
50%        25.000000
75%        25.000000
max        48.300000
Name: Visibility (km), dtype: float64

In [109]:
# Pandas DataFrame Opersations

In [ ]:
# Pivot Table
